Calling Elastic Search

In [1]:
from elasticsearch import Elasticsearch

In [6]:
es = Elasticsearch(
    "https://localhost:9200",
    basic_auth=("elastic", "4UORufemVQ67-PTLj50o"),
    ca_certs=r"C:\Users\Yaksh\Downloads\elasticsearch-9.4.3-windows-x86_64\elasticsearch-9.4.3\config\certs\http_ca.crt"
)

es.ping()

True

In [12]:
import pandas as pd

df = pd.read_csv("tmdb_5000_movies.csv").loc[:499]

In [13]:
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [15]:
df.isna().value_counts()

budget  genres  homepage  id     keywords  original_language  original_title  overview  popularity  production_companies  production_countries  release_date  revenue  runtime  spoken_languages  status  tagline  title  vote_average  vote_count
False   False   False     False  False     False              False           False     False       False                 False                 False         False    False    False             False   False    False  False         False         298
                True      False  False     False              False           False     False       False                 False                 False         False    False    False             False   False    False  False         False         189
                False     False  False     False              False           False     False       False                 False                 False         False    False    False             False   True     False  False         False          10
                True      False  False     False              False           False     False       False                 False                 False         False    False    False             False   True     False  False         False           3
Name: count, dtype: int64

In [16]:
df.fillna("None",inplace=True)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,79000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",http://www.themysteriousisland.com/,72545,"[{""id"": 10364, ""name"": ""mission""}, {""id"": 4089...",en,Journey 2: The Mysterious Island,Sean Anderson partners with his mom's boyfrien...,40.723459,"[{""name"": ""New Line Cinema"", ""id"": 12}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-01-19,355692760,94.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Believe the Impossible. Discover the Incredible.,Journey 2: The Mysterious Island,5.8,1030
496,78000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",None,109451,"[{""id"": 1436, ""name"": ""inventor""}, {""id"": 1063...",en,Cloudy with a Chance of Meatballs 2,After the disastrous food storm in the first f...,41.247402,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-09-26,248384621,95.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Something big was leftover.,Cloudy with a Chance of Meatballs 2,6.4,915
497,78000000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 53, ""name...",None,9533,"[{""id"": 6259, ""name"": ""psychopath""}, {""id"": 10...",en,Red Dragon,"Former FBI Agent Will Graham, who was once alm...",10.083905,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...","[{""iso_3166_1"": ""DE"", ""name"": ""Germany""}, {""is...",2002-09-29,209196298,124.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Before the Silence.,Red Dragon,6.7,1115
498,100000000,"[{""id"": 37, ""name"": ""Western""}, {""id"": 12, ""na...",None,2023,"[{""id"": 643, ""name"": ""horse race""}, {""id"": 267...",en,Hidalgo,"Set in 1890, this is the story of a Pony Expre...",16.759252,"[{""name"": ""Casey Silver Productions"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2004-03-05,108103450,136.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Unbridled. Unbroken. Unbeaten.,Hidalgo,6.5,318
499,79000000,"[{""id"": 35, ""name"": ""Comedy""}]",http://www.jackandjill-movie.com/,71880,"[{""id"": 179431, ""name"": ""duringcreditsstinger""}]",en,Jack and Jill,"Jack Sadelstein, a successful advertising exec...",22.132418,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2011-11-11,149673788,91.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,His twin sister is coming for the holidays... ...,Jack and Jill,4.1,604

Data frame contertion to Bert

In [17]:
from sentence_transformers import SentenceTransformer

C:\Users\Yaksh\AppData\Roaming\Python\Python314\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [18]:
model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")
embeddings = model.encode([
    "The weather is lovely today.",
    "It's so sunny outside!",
    "He drove to the stadium.",
])
similarities = model.similarity(embeddings, embeddings)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 5874.79it/s]
MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [43]:
df["Description_vector"] = df["overview"].apply(lambda x : model.encode(x))

In [44]:
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,Description_vector
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,"[0.022751985, 0.039562643, 0.02491665, -0.0525..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"[0.038600083, -0.010578605, 0.00684043, -0.030..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,"[-0.022166273, -0.02062903, -0.0020858352, -0...."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,"[0.02817617, 0.010714095, -0.008729371, -0.036..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,"[0.01899107, -0.012992109, 0.036445983, -0.028..."

In [30]:
# wether es is online or not
es.ping()

True

In [52]:
from sample_index import index_mappings

ImportError: cannot import name 'index_mappings' from 'sample_index' (a:\Faltu projects\Recommendation_System\sample_index.py)

In [ ]:
es.indices.create(index="all_movies", mappings = index_mapping)

BadRequestError: BadRequestError(400, 'resource_already_exists_exception', 'index [all_movies/0vpDs08SRIyq-4ndhifBnQ] already exists')

In [47]:
record_list = df.to_dict("records")

In [41]:
print(record_list[0])

{'budget': 237000000, 'genres': '[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]', 'homepage': 'http://www.avatarmovie.com/', 'id': 19995, 'keywords': '[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]', 'original_language': 'en', 'original_title': 'Avatar', 'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.', 'popularity': 150.437577, 'production_companies': '[{"name": "Ingenious Film Partners", "id": 289}, {"name": "Twentieth Century Fox Film Corporation", "id": 306}, {"name": "Dune Entertainment", "id": 444}, {"name": "Lightstorm Entertainment", "id": 574}]', 'production_countries': '[{"iso_3166_1": "US", "name": "United States of America"}, {"iso_3166_1": "GB", "name": "United Kingdom"}]', 'release_date': '2009-12-10', 'revenue': 2787965087, 'runtime': 162.0, 'spoken_languages': '[{"iso_639_1": "en", "name": "English"}, {"iso_639_1": "es", "name": "Espa\\u00f1ol"}]', 'status': 'Released', 'tagline': 'Enter the World of Pandora.', 'title': 'Avatar', 'vote_average': 7.2, 'vote_count': 11800, 'Description_vector': array([[ 2.27519851e-02,  3.95626426e-02,  2.49166507e-02,
        -5.25297783e-02, -1.69967825e-03,  1.64064039e-02,
         2.74929926e-02,  2.61900462e-02, -1.36253517e-02,
         4.66544144e-02,  4.95241433e-02, -5.75042814e-02,
         2.98142564e-02,  5.81491999e-02,  2.11293846e-02,
        -1.05291754e-02,  5.97463027e-02,  7.76326749e-03,
         4.98822555e-02, -2.01126672e-02, -6.31838441e-02,
        -1.10499701e-02, -1.90613456e-02, -3.75991762e-02,
         1.18330725e-01, -5.08208200e-03,  4.21730103e-03,
         1.30330026e-02, -2.91394293e-02, -8.60733353e-03,
        -3.34522827e-03,  7.48202065e-03,  2.10776851e-02,
         1.84898861e-02,  1.49702589e-06, -4.54876311e-02,
        -3.96365719e-03, -2.82713789e-02,  1.01039093e-03,
        -3.77432555e-02,  6.04242310e-02, -3.33202146e-02,
        -6.03135582e-03, -2.32530553e-02, -1.68884767e-03,
        -5.90990037e-02,  2.72197295e-02,  3.74852382e-02,
         3.18920575e-02, -1.36393905e-02,  9.39562637e-03,
         1.13776311e-01, -7.74736032e-02, -5.69113763e-03,
        -3.34728584e-02,  2.70791408e-02, -3.47453728e-02,
         1.25909578e-02,  8.58208165e-02, -4.84951725e-03,
        -1.41076986e-02,  1.52170351e-02, -5.14372960e-02,
         5.13029099e-02, -3.45942974e-02,  2.33508218e-02,
         3.29825915e-02,  7.23953079e-03,  2.80293059e-02,
         3.75316944e-03,  1.42479539e-02,  9.55784041e-03,
         1.64979193e-02,  7.20315650e-02, -6.18709344e-03,
         5.79919741e-02, -2.26626415e-02,  4.88996394e-02,
         8.59460700e-03, -6.90300986e-02,  3.43639180e-02,
         1.43557983e-02,  5.90570690e-03,  9.73391812e-03,
        -6.25617290e-03,  3.71745341e-02, -1.22637209e-02,
         1.95187554e-02, -3.66938091e-03, -3.34383734e-02,
         3.10042687e-02,  4.34858277e-02,  3.38372253e-02,
        -9.19274613e-03,  1.03682922e-02, -1.65368952e-02,
        -1.49146831e-02, -1.30306212e-02, -1.86037533e-02,
        -7.21290056e-03,  7.35499838e-04,  3.31461616e-02,
         1.68880876e-02,  3.55649367e-02,  9.23011638e-03,
         5.48933819e-02,  2.78140940e-02,  2.64934003e-02,
         4.92143966e-02,  5.77528849e-02, -3.00207851e-03,
         2.48320382e-02,  2.85229459e-02,  2.33856440e-02,
         4.13793847e-02, -3.08700074e-02,  5.97704351e-02,
        -4.04903218e-02,  5.21646813e-03, -3.09483130e-02,
        -7.06343204e-02,  9.72494110e-03, -4.53539677e-02,
         5.90187311e-03,  1.32159854e-04, -3.06058004e-02,
         4.91703562e-02, -1.16640376e-02,  5.92624769e-04,
        -1.85308289e-02, -2.11679321e-02, -4.07654494e-02,
         2.00631632e-03, -9.71292518e-03,  4.21266595e-04,
         8.49736035e-02,  1.59394967e-05,  1.48631260e-02,
        -2.30162274e-02,  4.56089526e-02,  6.84225410e-02,
        -2.61243805e-03, -7.72880716e-03, -7.59495329e-03,
         1.06333144e-01, -1.37886712e-02, -1.61505733e-02,
        -3.27074230e-02, -1.02136014e-02, -1.55210225e-02,
         6.15776815e-02,  6.98888004e-02,  4.17299457e-02,
         3.10543124e-02,  2.91979220e-02,  2.43093818e-02,
        -2.05731322e-03,  1.57016777e-02,  2.71121860e-02,
        -1.70239538e-03,  5.82737029e-02,  7.09860073e-03,
        -2.97292639e-02, -6.40809815e-03, -4.23383974e-02,
         1.56125640e-02, -3.02998293e-02,  2.09784159e-03,
         6.66064993e-02,  6.09182864e-02,  8.12037010e-03,
        -3.15956958e-02, -2.57606804e-02, -2.89529236e-03,
         2.15336923e-02, -3.98289524e-02, -7.63551667e-02,
         1.04287164e-02, -5.97812841e-03,  2.20318250e-02,
        -4.33017015e-02, -8.14301893e-02,  2.82582361e-02,
        -3.25749442e-02,  1.12188337e-02, -3.74076776e-02,
        -4.58598733e-02,  8.50035716e-03, -1.10747002e-03,
         3.90181839e-02,  4.09764312e-02, -1.78551767e-02,
         7.40828887e-02,  3.17995325e-02,  4.08303328e-02,
         5.45487460e-03, -1.76804909e-03,  3.56444307e-02,
         2.51407661e-02, -1.83705259e-02,  1.64340641e-02,
         2.60993578e-02,  3.04024741e-02, -1.15284473e-02,
         2.85074338e-02, -2.25751884e-02, -2.89819594e-02,
        -2.14613006e-02,  1.33409081e-02,  4.48600575e-02,
        -3.96594591e-02, -7.55724870e-03,  6.18648976e-02,
        -2.82679293e-02, -1.13806548e-03,  1.54422177e-02,
        -3.23688518e-03,  1.55872554e-02, -9.25644711e-02,
         2.85948403e-02,  5.86821791e-03, -5.89294396e-02,
        -5.46482056e-02,  1.23478491e-02,  2.26769410e-02,
        -2.51576882e-02,  1.80913452e-02, -8.91304947e-03,
         5.43370433e-02,  1.95382740e-02,  1.21539244e-02,
         2.84401756e-02, -2.16215998e-02, -3.84346657e-02,
         2.67544165e-02,  3.02400328e-02,  8.55403196e-05,
         4.52413969e-02,  1.59942277e-03, -4.74534184e-02,
         3.47024873e-02,  1.05288357e-01, -4.74923383e-03,
         1.25841331e-02,  8.18373729e-03,  2.53467914e-02,
        -5.01760133e-02,  6.33844221e-03,  1.01598306e-02,
         5.48370928e-03,  6.37506247e-02, -2.62278635e-02,
        -5.03578372e-02, -3.25354491e-03,  2.00711079e-02,
        -6.49679871e-03, -4.18489538e-02,  1.45483073e-02,
        -2.07991078e-02,  7.99561327e-04,  3.72509323e-02,
         7.20919156e-03,  6.76942058e-03, -2.63572112e-02,
         1.45539343e-02,  3.74100246e-02,  5.57885366e-03,
         4.10998939e-03, -3.64266671e-02, -9.87321977e-03,
         1.26036648e-02,  3.56653258e-02,  1.48785012e-02,
        -1.51577708e-03,  4.88479435e-03,  1.08156260e-02,
        -9.62153822e-02,  2.50294581e-02, -4.45346683e-02,
        -2.60626134e-02,  1.72413737e-02,  7.00150207e-02,
         9.47328378e-03,  4.58458578e-03,  2.25006230e-02,
         2.83649322e-02,  1.13626895e-02, -1.44641800e-02,
        -7.22214580e-02,  1.82642054e-03,  9.00066923e-03,
         1.52652124e-02, -2.80427039e-02, -1.15125580e-02,
         2.19665430e-02, -1.89268123e-02, -1.80449206e-02,
        -4.34854114e-03,  1.85257122e-02, -1.07565371e-03,
         1.26973897e-01,  3.91125642e-02,  3.08830068e-02,
        -2.37013940e-02, -2.34568454e-02,  3.40727461e-03,
         2.61760708e-02,  7.43918680e-03, -3.24524939e-02,
        -5.59304431e-02, -3.51853669e-02,  5.20802364e-02,
         1.82078276e-02, -7.25505203e-02, -4.37626941e-03,
        -4.52780649e-02, -3.46391601e-03, -7.54545163e-03,
        -2.32464578e-02,  2.52452381e-02, -4.79542557e-03,
         1.97255816e-02,  2.42249593e-02, -6.54486334e-03,
         1.33523799e-03, -1.79959182e-02,  6.75292034e-03,
        -1.79919042e-02,  3.59384008e-02, -3.52565572e-02,
        -1.00095784e-02,  5.16331270e-02, -1.69089176e-02,
        -3.07837483e-02,  7.93433711e-02, -5.05535342e-02,
        -4.83036600e-03, -3.61827351e-02, -4.38418165e-02,
        -8.26213043e-03,  3.53293121e-03,  1.24501949e-02,
        -1.49818948e-02, -1.79454789e-03, -7.23685313e-04,
         1.57099217e-02, -4.12772559e-02,  3.40937227e-02,
         1.39722126e-02, -3.54374833e-02,  3.20427641e-02,
         7.07325861e-02, -7.68302707e-03,  2.09775995e-02,
         3.47101898e-03, -4.57374752e-02,  3.71313393e-02,
         8.34421739e-02,  5.37429936e-02, -1.01253176e-02,
        -3.38422507e-02,  7.76451640e-03,  4.21656258e-02,
        -5.05081713e-02,  1.43495910e-02,  2.15942599e-02,
         2.40055323e-02,  4.29525226e-02,  4.92832400e-02,
        -3.54854614e-02, -2.92617101e-02, -4.18288223e-02,
        -5.72053604e-02,  1.08332718e-02,  1.19176619e-02,
        -8.60462785e-02, -1.34994602e-02, -3.47844921e-02,
        -2.23468766e-02,  6.88955607e-03,  9.25750472e-03,
         3.84644940e-02,  2.37703547e-02, -2.64101420e-02,
         5.28821684e-02, -9.41183325e-03, -7.03907805e-04,
        -6.56799693e-03, -7.39147933e-03, -6.24596374e-03,
         1.03419200e-02,  8.28734133e-03, -3.12360283e-02,
        -5.62592745e-02, -1.78504514e-03, -1.71361689e-03,
        -5.07302396e-02,  1.93706974e-02,  1.54986773e-02,
         5.19675808e-03, -6.15925528e-02,  8.49744156e-02,
        -2.81628612e-02,  7.51784742e-02, -3.35770915e-03,
        -5.99733903e-04,  1.15233818e-02,  9.51517001e-03,
        -4.60376590e-02,  6.02719449e-02,  5.91201372e-02,
         1.14753339e-02,  8.36995989e-03,  1.01715960e-02,
        -9.02494565e-02, -1.16789443e-02, -3.33668292e-02,
        -2.51859259e-02, -4.72774776e-03, -1.90680809e-02,
         8.96504428e-03,  3.38137932e-02,  1.44908810e-02,
        -6.20478094e-02,  1.15472011e-01, -2.96165440e-02,
         2.98892874e-02,  2.92989463e-02, -1.85596310e-02,
        -3.18361782e-02, -1.31902443e-02,  3.64757376e-03,
        -1.57531444e-02,  2.50503067e-02, -4.88811545e-02,
        -8.91000126e-03,  3.22137401e-02, -2.06969790e-02,
        -1.06117465e-02, -1.40183382e-02, -2.10049525e-02,
         1.77222490e-02,  7.66573381e-03,  2.58384589e-02,
        -1.90030560e-02, -1.75549444e-02,  1.63873173e-02,
        -2.77529433e-02,  2.40527634e-02, -6.28482783e-04,
         2.39518322e-02,  2.42329761e-02, -3.38932984e-02,
        -1.24137014e-01, -5.73467650e-02,  2.10570823e-03,
        -2.74720471e-02,  1.53823039e-02,  6.18835306e-03,
         4.25621085e-02,  7.05817202e-03,  1.20901074e-02,
        -6.81684613e-02,  3.77196744e-02, -9.01269075e-03,
        -1.88799705e-02,  1.68850217e-02, -2.10181996e-02,
         3.26290019e-02, -3.07839289e-02,  1.29787466e-02,
        -4.19696048e-02,  9.45838541e-03, -2.70315111e-02,
        -8.12820643e-02, -3.99487428e-02, -1.56455413e-02,
        -2.09205430e-02,  4.24306579e-02, -1.33605823e-02,
         8.85776430e-03,  5.13747595e-02, -8.19606707e-02,
         2.79196985e-02, -1.11452248e-02, -6.42093644e-02,
        -3.86150889e-02, -3.69928777e-03, -2.75986549e-02,
         8.54336023e-02, -7.56495539e-03,  5.87665616e-03,
         1.41814090e-02, -6.93540275e-02,  2.25808956e-02,
        -3.17097828e-02, -6.29054978e-02,  3.23529691e-02,
         4.54097427e-02, -5.99202178e-02, -2.50182766e-02,
        -4.51827496e-02, -3.16361524e-02,  8.32079351e-02,
        -1.57800522e-02, -6.58009127e-02, -1.49053428e-02,
         5.28834667e-03,  1.58063602e-02, -4.28185761e-02,
        -3.98791395e-02,  3.17881554e-02, -2.06530876e-02,
        -8.25884044e-02,  7.51312897e-02,  1.25542060e-02,
         9.56362672e-03, -6.73760567e-03, -6.19770139e-02,
         2.04885937e-02, -1.04138125e-02, -8.94604344e-03,
        -9.50158909e-02, -4.89815921e-02, -8.58965423e-03,
         7.36925332e-03,  6.83848485e-02,  2.94255409e-02,
         9.36347619e-02,  3.89722362e-02,  1.76487472e-02,
         8.19527451e-03,  8.55421796e-02,  3.85376951e-03,
        -2.13539340e-02,  3.81958336e-02, -8.42651278e-02,
         8.89639184e-02, -3.00280247e-02, -9.86772869e-03,
        -1.91434771e-02,  5.20919636e-03, -1.60059575e-02,
         7.52446502e-02,  2.74382569e-02, -2.24473141e-02,
         2.44427789e-02, -7.43080117e-03, -5.05436659e-02,
         4.12092321e-02, -8.44586827e-03, -1.96267967e-03,
        -2.13383697e-02,  4.11953451e-03,  2.62200050e-02,
        -5.79263853e-33,  2.49703284e-02, -7.42020411e-03,
        -4.44579832e-02,  3.40629136e-04, -5.33045121e-02,
        -1.31498473e-02, -2.56218929e-02,  9.60882753e-03,
         2.64169686e-02, -8.57499242e-03,  4.76603583e-02,
         1.41110737e-02, -1.90044206e-03, -1.41662313e-02,
         1.14604225e-02,  3.81562077e-02, -2.56225318e-02,
         2.42422540e-02, -4.82888136e-05, -3.87992784e-02,
         5.52698933e-02,  2.11341288e-02, -6.84501976e-02,
        -7.23541379e-02, -9.91377980e-03, -2.18179729e-02,
        -2.71571800e-02,  8.09643045e-03, -3.33502814e-02,
         3.13388295e-02,  1.40878269e-02,  2.52694823e-02,
        -7.14372098e-03, -2.31244974e-03, -1.81207038e-03,
         8.88882671e-03, -2.35913298e-03,  4.83623333e-02,
         3.29072252e-02, -2.11795028e-02,  1.10320421e-02,
        -3.94532271e-02, -2.22273320e-02, -2.93291304e-02,
         1.09012909e-02, -2.55202875e-02, -1.81969609e-02,
        -8.32410809e-03,  1.41164018e-02, -6.63983896e-02,
        -5.06822728e-02,  2.55421158e-02,  2.20299456e-02,
        -1.77157242e-02,  7.09109707e-03,  2.38174796e-02,
        -5.31866178e-02,  3.16339359e-02,  5.10454439e-02,
        -1.18204961e-02, -2.65670419e-02,  5.58878854e-02,
        -3.75542603e-03, -1.11558959e-02,  2.28868313e-02,
         5.01396134e-03, -5.87610900e-02,  1.14960689e-02,
        -2.21868940e-02,  2.91765276e-02, -2.69696023e-02,
         1.34917805e-02,  5.28377108e-02, -3.74508323e-03,
        -5.91641590e-02, -2.12468188e-02, -2.78233867e-02,
        -2.94723595e-03,  8.93176720e-02, -2.50579733e-02,
         2.31896117e-02,  2.39127055e-02, -1.67354103e-02,
         1.01659838e-02,  1.92123838e-02, -3.90893370e-02,
         3.11382790e-03,  2.28938693e-03, -4.02053446e-02,
        -4.35988157e-04, -2.95134000e-02, -2.76957545e-02,
        -1.71186868e-02,  3.06704435e-02,  1.02340663e-02,
        -5.55752814e-02,  2.02502422e-02,  4.44007572e-03,
         7.91882630e-03, -3.88950482e-02,  7.09935129e-02,
        -2.61397171e-03,  1.10596907e-03, -8.60984102e-02,
         5.26922457e-02, -1.56139219e-02, -6.13973960e-02,
        -2.23833229e-03,  1.51230413e-02, -9.51112714e-03,
         3.35055515e-02, -7.30182454e-02, -2.95242853e-02,
         4.95833755e-02, -1.74831748e-02, -7.46234730e-02,
         1.19051430e-03,  8.78389273e-03,  5.42990211e-03,
        -5.13487756e-02,  3.96026708e-02,  2.08643153e-02,
        -4.02108543e-02,  6.49866909e-02, -6.54888079e-02,
         1.17655909e-02, -5.73828770e-03,  5.74220456e-02,
        -3.67260762e-02, -2.77814944e-03, -2.23016907e-02,
         3.47590111e-02,  2.31289391e-07, -1.43571170e-02,
        -2.24293657e-02,  1.56513378e-02, -4.03720662e-02,
        -4.85036820e-02,  2.96359602e-02,  1.20000942e-02,
         2.41384003e-02, -3.87557931e-02, -2.54483186e-02,
         1.45728495e-02,  1.68494247e-02, -3.50088514e-02,
        -8.58859718e-03,  5.25537692e-03,  7.11000040e-02,
         3.11475843e-02, -8.12604502e-02,  5.91834215e-03,
        -6.18231967e-02,  6.43316433e-02, -4.27852757e-02,
        -2.90276390e-03, -1.74266081e-02, -3.23577821e-02,
         2.01760717e-02, -9.49518848e-03, -1.02553023e-02,
        -4.95340563e-02, -6.29969090e-02, -4.43827510e-02,
         2.56939568e-02, -4.53108735e-02,  1.73276290e-02,
        -2.27982253e-02, -1.28018297e-02,  8.96316022e-02,
         3.60397920e-02, -1.08378241e-02, -1.45364157e-03,
        -9.10396874e-03,  5.33726737e-02, -5.44846244e-02,
        -2.75635328e-02, -7.46050803e-03,  1.29893105e-02,
        -4.58891205e-02, -4.81869318e-02, -1.40694864e-02,
         2.32431758e-02,  4.77845706e-02,  2.92844381e-02,
        -1.26815438e-02, -1.18130445e-02, -4.78894450e-03,
         7.71922665e-03,  9.09483805e-03, -9.27512534e-03,
         3.19393165e-02,  6.10243082e-02, -2.81149633e-02,
         1.22632170e-02,  3.71992551e-02, -1.37887262e-02,
         4.89252992e-02, -3.56917679e-02, -2.73563210e-02,
         2.16889958e-34, -1.67213306e-02, -6.96490938e-03,
        -1.86272897e-02, -4.52953093e-02, -1.12112993e-02,
        -1.26869148e-02, -8.09350908e-02,  6.88412366e-03,
         1.73311587e-02,  1.16786286e-02, -1.97656415e-02]], dtype=float32)}

In [48]:
for record in record_list:
    es.index(index = "all_movies" , document = record , id = record["id"])